version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    container_name: handle_backend_web
    volumes:
      - ./:/var/www
    ports:
      - "8093:80"
    links:
      - app
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: "3"
  nodejs:
    image: node:21-alpine
    container_name: handle_backend_nodejs
    volumes:
      - ./:/var/www/
    working_dir: /var/www
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: "3"
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
      args:
        - USER=${USER}
    container_name: handle_backend_app
    volumes:
      - ./:/var/www
    links:
      - database
    environment:
      - "DB_HOST=database"
      - "DB_PORT=3306"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: 5m
        max-file: "3"
  database:
    image: mysql:8.0
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=handle_backend"
    ports:
      - "33065:3306"
    networks:
      - backend
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: handle_backend_phpmyadmin
    links:
      - database
    ports:
      - "8094:80"
    environment:
      - "PMA_HOST=database"
      - "PMA_USER=root"
      - "PMA_PASSWORD=secret"
    networks:
      - backend
networks:
  backend:
    driver: bridge
