version: "3.8"

services:
    app:
        image: php:8.2
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel
    web:
        build:
            context: ./
            dockerfile: dockerfile
        container_name: handle_backend_web
        volumes:
            - .:/var/www
        ports:
            - "8080:80"
        networks:
            - backend
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
                max-file: "3"
    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: handle_backend
        ports:
            - "8090:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: handle_backend_phpmyadmin
        depends_on:
            - db
        ports:
            - 8081:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root_password
        networks:
            - laravel
volumes:
    dbdata:

networks:
    laravel:
    backend:
